### ISSUE TITLE
Create database table to store projects

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#10]
Sketches:
- [projects.json](https://github.com/climateconnect/climateconnect/blob/develop/public/data/projects.json)
- [project_status_metadata.js](https://github.com/climateconnect/climateconnect/blob/develop/public/data/project_status_metadata.js)

**Comment by positiveimpact** [comment]
A sketch of how the table structure for this could look like can be found here:
https://github.com/climateconnect/climateconnect/blob/develop/public/data/projects.json

**Comment by ddhanesha** [comment]
Assigning this task to myself.
