### ISSUE TITLE
Bug: Organization creation translation issues

### ISSUE THREAD

**Issue by JoshKornfeld** [climateconnect/climateconnect#1038]
**Describe the bug**

Using the automatic translate feature when creating an organization does not save the changes made.
Note: seems you need to input English text first and then translations would be correctly generated.

**To Reproduce**
1. Be on the German version of the website
2. Go through the process of creating an organization
3. Click on 'Erstellen'
4. You should be on the translation page
5. Click on "Automatisch Übersetzten"
6. Click on "Veröffentlichen"
7.  See error; Change the language to English, the summary / about text will not change to the values set.

**Expected behavior**
Pressing the save button within the check translations interface should save the changes the user entered or results generated.

**Comment by positiveimpact** [comment]
A video would be really helpful for this @tobiasrehm

**Comment by tobiasrehm** [comment]
I couldn't reproduce this anymore. After creating the organisation user is not redirected to the check translation section as stated. Translation worked fine. The only issue I could find: If you input text in the "wrong" language it gets translated anyway which can lead to mixed-up translations. German text as English and vice versa. This never happened until now so should be fine.
