### ISSUE TITLE
Bug: Organization summary text length

### ISSUE THREAD

**Issue by JoshKornfeld** [climateconnect/climateconnect#1039]
**Describe the bug**
Tooltip says the short description is max. 280 characters, but this is not the case.

**To Reproduce**
1. Go to 'edit organization'
2. In the summary text field enter a string greater than 280 characters
3. Click save
4. See error; it will save without throwing an error

**Expected behavior**
An error message should appear and prevent user from using more than 280 characters for the summary of an organization.

**Comment by tobiasrehm** [comment]
This is fixed
