### ISSUE TITLE
Bug: Organization description fields not saving

### ISSUE THREAD

**Issue by JoshKornfeld** [climateconnect/climateconnect#1045]
**Describe the bug**
When changing the about text or short description of an organization from the "check translations" interface, the save button would not change these fields to the new value.

**To Reproduce**
1. Go to an organization of which you have admin rights for
2. Click on 'edit organization.'
3. Scroll down to 'check translations'
4. For either the short description or the about field, input some new text
5. Click save
6. See error; the fields don't change

**Expected behavior**
The expected behavior is that the fields do not change after clicking save.

**Comment by positiveimpact** [comment]
Closed by #1046
