### ISSUE TITLE
Bug: Clicking the close button on notifications has a very delayed response

### ISSUE THREAD

**Issue by JoshKornfeld** [climateconnect/climateconnect#1050]
**Describe the bug**
Closing a notification via the close button is very slow. This makes it unclear for the user to know whether it worked or not.

**To Reproduce**
1. Receive a notification
2. Click on the bell icon
3. Press the close button on the notification
4. See error (Takes a long time to disappear)

**Expected behavior**
The notification should disappear much faster -> visually should be instantly deleted via frontend, rather than wait for the backend.

**Comment by positiveimpact** [comment]
Closed by #1060
