### ISSUE TITLE
GitHub actions bug: Fix the `lint frontend` workflow

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#1053]
**Describe the bug**
The GitHub Actions workflow `.github/workflows/pull_request-lint-frontend.yml` to ensure that lint passes in the frontend is currently broken. The error it throws is the following: `the 'uses' attribute must be a path, a Docker image, or owner/repo@ref` so it seems like the workflow file is invalid.

**To Reproduce**
1. Go to [https://github.com/climateconnect/climateconnect/actions/runs/3035701713](https://github.com/climateconnect/climateconnect/actions/runs/3035701713)
2. See the error
3. This problem occurs on every run of the workflow

**Expected behavior**
The workflow should run `yarn lint`and return whether it passed or not

**Comment by tobiasrehm** [comment]
what about this one? Still relevant? @positiveimpact

**Comment by positiveimpact** [comment]
Seems to be fixed
