### ISSUE TITLE
Refactor NotificationSerializer

### ISSUE THREAD

**Issue by JoshKornfeld** [climateconnect/climateconnect#1079]
**Is your feature request related to a problem? Please describe.**
NotificationSerializer is bloated and should be refactored and split up into sub serializers.

**Describe the solution you'd like**
Similar to how `ProjectSuggestionSerializer` is a child of `ProjectSubSerializer` in `backend/organization/serializers/project.py` we should make one parent NotificationSerializer and one child serializer for each notification type.

**Comment by tobiasrehm** [comment]
Not sure about this one. @positiveimpact @ddhanesha Do you think this is needed?

**Comment by positiveimpact** [comment]
This is so low priority that I would close it for now
