### ISSUE TITLE
Create API routes for creating and editing projects

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#11]
Called by: 
- #52

Functionality: 
- Insert or edits a personal project or a project of an organization, in which you are an administrator, in the projects table

Restricted to:
- logged in users
- if they are creating a project of an organization: admins of that organization

**Comment by ddhanesha** [comment]
Started working on APIs.

**Comment by ddhanesha** [comment]
@positiveimpact just to be clear all projects are attached to an organization, correct?

**Comment by positiveimpact** [comment]
> @positiveimpact just to be clear all projects are attached to an organization, correct?

Either to an organization or to an individual @ddhanesha
