### ISSUE TITLE
Set up API token authentication for users

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#110]
Is related to #123

**Comment by ddhanesha** [comment]
Started looking into token authentication. There are two approaches we can take. 1) Use django rest's `built in token authentication`. 2) Use [django-rest-knox](https://github.com/James1345/django-rest-knox) library for token authentication. 

Option 2 is much secure to use. Here are the pros django-rest-knox vs DRF token authentication
http://james1345.github.io/django-rest-knox/

**Comment by positiveimpact** [comment]
I think we'd actually benefit from all the advantages described in the blog post, so my vote is definitely for django-rest-knox.
