### ISSUE TITLE
Upgrade Azure postgreSQL instance from version 10 to 14

### ISSUE THREAD

**Issue by ddhanesha** [climateconnect/climateconnect#1123]
**Is your feature request related to a problem? Please describe.**
We received an email for Azure that the current support for postgreSQL 10 is expiring in 3 days. That is why we would have to upgrade our postgreSQL instance to version 14.

**Comment by positiveimpact** [comment]
Azure did not allow us to make a postgres flexible server instance in Germany West Central. Therefore I instead upgraded to Postgres 11 (the highest possible) with a single instance. As soon as server space gets available we should upgrade to Postgres 14 as planned.
