### ISSUE TITLE
Create API routes for editing your account page and your account settings

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#113]
Called by:
- #94 

Arguments:
- token of logged in user
- object of the properties, that should be changed

Functionality:
- edit any of the content on your account page
- change your password
- change your email address
- apply to join an organization
- leave an organization

Restrictions:
- logged in users
- you can only edit your own account page

**Comment by ddhanesha** [comment]
@positiveimpact can you point me to the UI design so the API design is relevant and easier to implement in the frontend?
