### ISSUE TITLE
Bug: Filters are unapplied when switching tabs

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#1138]
When applying a filter on the browse page or any hub page they should work as follows:
- when switching tabs all current filters that can also be applied to the new tab should also be applied.

Currently there are the following issues:
- When switching tabs the location filter is still shown if it was applied before but won't be applied to the new tab

**Comment by tobiasrehm** [comment]
This seems to be fixed, can't reproduce
