### ISSUE TITLE
Feature: Implement restrictions for cold-contacting users

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#1144]
We've had a few cases of users signing up and just messaging 20+ people in one hour with "Hello" or a similar message that provides no value and could be classified as spam. We need to make sure that messages on Climate Connect have value for the receiver and will therefore implement restrictions to prevent this type of behavior.
The following restrictions should be implemented:
- Require a first reach-out message to have at least 10 words. This should only apply to contacting somebody who you've never chatted with before
- For new accounts only allow to cold-contact 5 new people per day. Again this should only apply to contacting somebody who you've never chatted with before.
- Add a field is_user_muted to UserProfile which we can tick through the API to temporarily or permanently stop users from sending messages. Make sure the chat API respects this property and prevents you from sending messages if the value is True.

**Comment by tobiasrehm** [comment]
What is the status of this? Isn't this implemented? @positiveimpact @ddhanesha

**Comment by positiveimpact** [comment]
It's implemented. closed.
