### ISSUE TITLE
Create API route(s) to get project(s)

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#119]
Called by:
- #14
- #18 
- the index.js page

Functionality:
- get project by id
- get project by search/filter terms
- get most relevant projects (for front page)

Restrictions:
- none

**Comment by ddhanesha** [comment]
`get most relevant projects (for front page)`

What do you mean by this? Are then any special filters that we would be using. Or is it for future development?

**Comment by positiveimpact** [comment]
> `get most relevant projects (for front page)`
> 
> What do you mean by this? Are then any special filters that we would be using. Or is it for future development?

We'll need a basic algorithm to decide which projects to show on the front page. Doesn't have to personalized for launch, but should also not show completely random projects. We need to do this before launch, but I wouldn't give to too high priority for now.
