### ISSUE TITLE
Bug: Project drafts trigger a notification for users that follow the orgnaisation

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#1200]
**Describe the bug**
If a Project is shared by an Organisation and saved as a draft, followers of that organisation receive a notification.

**To Reproduce**
Steps to reproduce the behaviour:
1. Be part of an organisation and follow it 
2. share a project with that org and save it as a draft 
3. receive notification + you can view the project by clicking on it
Also works if its not your onw account that is following

**Expected behavior**
Notification for project drafts should not be send out

**Comment by ddhanesha** [comment]
Fix should be in production soon.
