### ISSUE TITLE
Create API route(s) to get organization(s)

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#121]
Called by:
- organization page
- #122 

Functionality:
- get organization(s) by id
- get organizations by search/filter terms
- optionally also return users and projects connected to this organization

Restrictions:
- none

**Comment by ddhanesha** [comment]
`optionally also return users and projects connected to this organization`

I think this should be a separate API Route.

**Comment by ddhanesha** [comment]
For restriction, should we do the same as we did for members API? Show some information to anonymous user and complete information to logged in users?
