### ISSUE TITLE
Bug: "View join requests" button on the project page is invisible

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#1252]
**Describe the bug**

**To Reproduce**
1. Create two user accounts on your local platform
2. Create a project with user account A
3. Log into user account B, go to the project page that user account A shared and click on "join"
4. If you now go to the project page while being logged in to user account A you'll see that there is a little green "1" indicator floating but the actual button to view project join requests is not visible.

**Expected behavior**
The "View join requests" button should use theme.palette.secondary.main as its background color, the button and the text on it should be clearly visible.

**Screenshots**
![Screenshot from 2023-07-13 07-52-03](https://github.com/climateconnect/climateconnect/assets/10531079/59c7452a-cadb-4465-a587-e8dfe1a827d4)

**Comment by tobiasrehm** [comment]
Even if this is not ideal, it seems to have been fixed:
![image](https://github.com/climateconnect/climateconnect/assets/64414429/8bac8032-5711-4538-b864-5de609947c35)
