### ISSUE TITLE
Bug: ClimateMatch Potsdam only outputs Ideas

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#1255]
**Describe the bug**
The results in for the ClimateMatch in Potsdam Hub only output ideas as results.

**To Reproduce**
1. Go to https://climateconnect.earth/de/climatematch?from_hub=potsdam
2. Do ClimateMatch
3. See Bug

**Expected behavior**
Results should include Orgs and Projects

**Screenshots**
![image](https://github.com/climateconnect/climateconnect/assets/64414429/771f5ec9-30a8-471e-8a2b-9567a42f4592)

**Comment by ddhanesha** [comment]
@tobiasrehm I have fixed the issue. It was not an issue with the code but with the location. In our database we have 4 Postdam, Germany location stored. The Postdam hub was only keeping track of one location. For now, I added all 4 locations to Postdam Hub. 

In the future I believe we would need to consolidate locations properly so our code does not create same location twice. Can you create an issue to address the larger issue in the future? cc @positiveimpact

**Comment by positiveimpact** [comment]
Created an issue for this @ddhanesha https://github.com/climateconnect/climateconnect/issues/1262
