### ISSUE TITLE
Create Diagram for table structure

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#126]
Doesn't have to be formal

**Comment by EvanHahn** [comment]
[Click here to see the interactive diagram](https://dbdiagram.io/d/5e7b66104495b02c3b88c124), or look at the static file below:

![Diagram](https://user-images.githubusercontent.com/777712/77800430-cd240b80-7044-11ea-9f64-67eb08ffc487.png)

Also see [this gist](https://gist.github.com/EvanHahn/f54683f01d8ab47e1cfa66c4f0742100) for the DBML file that produces this diagram.
