### ISSUE TITLE
Bug: Link on "Spenden" points to wrong language

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#1283]
**Describe the bug**
On the static pages in the Subnavigation the link on "Spenden" points to the english page instead of the german page:
![image](https://github.com/climateconnect/climateconnect/assets/64414429/0e09e8e5-7709-4a6d-94eb-d3dbd09cc0a4)

**Comment by positiveimpact** [comment]
I just tried and could not reproduce that

**Comment by tobiasrehm** [comment]
Ah sorry I described that a bit imprecise. Its only on the upper "Spenden" Text. So not in the dropdown menu but above
