### ISSUE TITLE
[Custom Hub Feature] Allow setting custom primary and secondary colors for specific hubs

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#1368]
## Why and What
We plan to customize the hub theme for certain external hubs. This customization can be handled in one of two ways:

**1.  Frontend-Only Approach:**

- Define the theme colors directly in the `Theme.ts` file.
- Use Next.js's useRouter hook to determine the current route and dynamically update the theme based on the route.

**2. Integration of Backend and Frontend:**

- The backend can provide an API for administrators to manage theme settings.

- The frontend can use this API to fetch the theme data and apply it dynamically via the `ThemeProvider`.

_These steps are required to achieve this feature._

- [x] Implement `hubTheme` and `hubThemeColor` tables in the backend:

       The `HubTheme` table will store foreign key relationships to the `HubThemeColor` and `Hub` tables.
       The `HubThemeColor` table will store color information related to the theme.

- [x] making Api to get Theme data

- [x] Integrated theme API data on the Front-end and dynamically generated the theme object

**Comment by fateme-ramezanpour** [comment]
[Design link](https://xd.adobe.com/view/1c7e3ef7-9ebf-4b92-9ac1-1b5bae1fddff-492d/)
