### ISSUE TITLE
Create API route for getting data of the logged in user

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#141]
Called by: 
- any page if the user is logged in

Arguments:
- `token` of the logged in user
- optional filter for only getting certain properties

Functionality:
- returns the entry of the logged in user from the users table, if filter is set, it only returns the filtered properties

Restrictions:
- You can only get the data of your own logged in account

**Comment by ddhanesha** [comment]
Assigning this task to myself.

**Comment by ddhanesha** [comment]
@positiveimpact can you elaborate on optional filters in the arguments section? What type of filters are we talking about?
