### ISSUE TITLE
Changing Project from Personal Project to Organization's project doesn't work

### ISSUE THREAD

**Issue by flomero** [climateconnect/climateconnect#265]

**Comment by positiveimpact** [comment]
Thanks for submitting!

Resolved by this commit: https://github.com/climateconnect/climateconnect/commit/d9b44ae7b8c5cfbd2eb6740d7e07b8b4b0ef07a5

**Comment by flomero** [comment]
I tried to change it again but after saving I get to an empty page saying "An unexpected error has occurred." @positiveimpact

**Comment by positiveimpact** [comment]
This was an error when setting the success message on the project page. Solved this in https://github.com/climateconnect/climateconnect/commit/fb5eb2798bbe1c156b6893ce3c0307be65df77f2.
