### ISSUE TITLE
Add description to sign up page clarifying that this is for your personal account

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#278]
Some people didn't know they could create an organization later, so they signed their personal account up as an organization profile

**Comment by susanchesnut** [comment]
@positiveimpact Where should this be located specifically (step 1 or 2 and placement)? Would something like "This sign up is for your personal account. You will have an opportunity to create/add an organization once signed up." be okay?

I feel like this wouldn't take long, but if explaining is longer than the effort, I can let you handle this item and I'll pick another.

**Comment by positiveimpact** [comment]
@susanchesnut It should be located in the first step at the same place where the explanatory text on https://climateconnect.earth/share is located. 
I would use "Here you can create your personal account. You will have an opportunity to create/add an organization once signed up."
