### ISSUE TITLE
Make filters change the url so you can send somebody a link of the filtered page

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#288]
For example when filtering by location="San Francisco", the url should automatically change to `urlEncode(climateconnect.earth/?location="San Francisco")`.
You could then send that link to a friend to directly link them to all the projects there are in San Francisco.

**Comment by positiveimpact** [comment]
@vliaskov Are you still actively working on this issue or should I re-assign it to somebody else?

**Comment by positiveimpact** [comment]
I will unassign this for now. You can of course assign it to yourself again if you're interested on working on it again in the future @vliaskov

**Comment by piperchester** [comment]
I'll take a look at this @vliaskov 👍
