### ISSUE TITLE
Add house icon as home button on the main page

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#298]
Some people did not understand that you can click on the logo to come to the main page, so a small house icon that acts as an additional home button should be added on the very left side of the current header links.

**Comment by marcobarrera** [comment]
Hi, may I work on this issue?

**Comment by positiveimpact** [comment]
> Hi, may I work on this issue?

Sure, you're welcome to work on it!
Contact me if you need any help with setting up the project locally!
