### ISSUE TITLE
Create database table(s) to store organizations

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#3]
Sketches for layout(s):
- [organization.json](https://github.com/climateconnect/climateconnect/blob/develop/public/data/organizations.json)
- [organization_info_metadata.json](https://github.com/climateconnect/climateconnect/blob/develop/public/data/organization_info_metadata.json)
- [organization_types.json](https://github.com/climateconnect/climateconnect/blob/develop/public/data/organization_types.json)

**Comment by positiveimpact** [comment]
A sketch of how the table structure could look like can be found here: https://github.com/climateconnect/climateconnect/blob/develop/public/data/organizations.json

**Comment by ddhanesha** [comment]
Assigning this task to myself.
