### ISSUE TITLE
Sort results in ListProjectsView based on url parameter

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#301]
# Current functions of the API
People can use the `/api/projects` endpoint to call the `ListProjectsView` view in `organization/views/project_views.py`. 
The view returns all projects on Climate Connect. It is also possible to add additional filters as query params, e.g. by calling ```https://api.climateconnect.earth/api/projects/?page=2&status=Idea&organization_type=NGO&collaboration=yes```.
# New function to add
Users should also be able to sort results by `newest`, `oldest` and `recommended` by adding a `sort_by=[option]`parameter to the url.

## Sorting by newest
Results should be sorted by descending id 

## Sorting by oldest
Results should be sorted by ascending id

## sorting by recommended(default)
No action needs to be taken. Results are automatically sorted by the `rating` column of the projects table.

**Comment by akshatashan** [comment]
merged in develop
