### ISSUE TITLE
Timeago currently shows "2 years" if the project is 1 year and one day old

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#305]
Always round down on years in timeago. For example on the project page.

**Comment by piperchester** [comment]
All of our Priority A backlog items are assigned; grabbing this one next.

**Comment by piperchester** [comment]
@ddhanesha could you and I pair on setting up project test data to be used for viewing the full project page some time? <img width="560" alt="Screen Shot 2020-12-11 at 4 35 54 PM" src="https://user-images.githubusercontent.com/1530684/101967032-f97db900-3bce-11eb-8252-db2096cac55b.png">

**Comment by ddhanesha** [comment]
Hey @piperchester, yeah sure. If you are around this weekend we can sync on resolving issues with test data.
