### ISSUE TITLE
Make decision on database system

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#31]
Possibilities are for example
-Elasticsearch
-MongoDB
-Postgres
-Redis Store for some parts

**Comment by positiveimpact** [comment]
Elasticsearch:
Pros: 
-The reason why Elasticsearch would be a good option is because it's good in certain cases when building recommender systems
-ES is great at stemming and tokenizing words
-Has partition tolerance and availability in CAP theorem
Cons: 
-lacks consistency: by default, changes only become readable after the index refreshes (default setting: every one second). It is possible to force refresh the index on important inserts, but this reduces performance.
-Indexing and especially updating a document is relatively expensive

MongoDB:
Pros:
-has partition tolerance and consistency in CAP theorem
Cons:
-lacks availability in CAP theorem with default settings
-theoretically supports full-text search through mongodb atlas
Cons:
-Isn't really good at full-text search (in the free version)

Our Use-Case:
Most filtering/searching/matching will be done through information such as "skills required by a project", "skills of a user", "projects a user follows" etc. Full-text search is not going to be used on launch and probably not for a while after. Therefore I believe for now MongoDB is the better choice.

**Comment by positiveimpact** [comment]
Unless we can identify a good reason to use a Non-SQL db, we should go with PostgreSQL due to its maturity.

**Comment by EvanHahn** [comment]
+1 for PostgreSQL. It feels like a stable, mature project that should meet our needs for a long time.
