### ISSUE TITLE
Multilevelselector doesn't show bottom border if you expand the lowest item

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#312]
![Screenshot from 2020-08-01 14-44-32](https://user-images.githubusercontent.com/10531079/89102015-8afd4300-d405-11ea-89cd-b3a5d2d06ed9.png)

**Comment by piperchester** [comment]
Going to take a stab at this! @positiveimpact if you know the URL or steps to repro this it's appreciated :pray: I'll take a look around though.

**Comment by piperchester** [comment]
Ok can repro it here: <img width="1021" alt="Screen Shot 2020-11-21 at 5 02 08 PM" src="https://user-images.githubusercontent.com/1530684/99891118-4cd99880-2c1b-11eb-9aa4-2ad18e9e5563.png">

**Comment by piperchester** [comment]
Update on this - have a fix in place, and am seeing if we can clean up some of the extra border styles in the process.
