### ISSUE TITLE
Add arrow to scroll to top when you're scrolled down

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#318]
When you're scrolled down really far, it's handy to be able to go up with just one click by clicking on an error that points to the top. This arrow should be placed on the bottom right corner when you're scrolled down on any tab on the main page.

**Comment by Olaleye-Blessing** [comment]
Can I work on this?

**Comment by positiveimpact** [comment]
> Can I work on this?
Sure! Let me know if you need any help or additional pointers to get started.

**Comment by positiveimpact** [comment]
Closed by #911
