### ISSUE TITLE
Create regular automated backups of our database

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#323]
https://django-dbbackup.readthedocs.io/en/master/configuration.html

**Comment by ddhanesha** [comment]
Deadline: Sunday 31st January, 2021
cc/ @positiveimpact

**Comment by ddhanesha** [comment]
Waiting on our cloud provider to respond.

**Comment by ddhanesha** [comment]
Now we have automated backups in our cloud provider service. Finally! 😅
