### ISSUE TITLE
Create API endpoint to allow users to leave a project team

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#325]
## Summary
At the moment you cannot leave a project once you're part of it, unless the administrator removes you.
## Behavior 
Remove the `ProjectMember` entry for this user in this project. 

_Update January 13:_
- If this `ProjectMember` has the role `Creator` in the project, they should have to pass an additional variable in the request appointing the new `Creator`. A project always has to have exactly one creator. 
- When the creator is updated, the user in the corresponding `ProjectParent` entry should also be updated to the new creator. 
- If the leaving user was  the only person in a project, a flag in the project's entry should be set marking it as inactive.
## Restrictions
You should only be able to remove your own `ProjectMember` entry, not one that corresponds to different users. Aka you can only make yourself leave a project and not anybody else

**Comment by bulve** [comment]
Currently, I don't have enough time to work on any of the items. I am moving it back to the backlog.

**Comment by positiveimpact** [comment]
Okay, thanks for giving a heads up!

**Comment by positiveimpact** [comment]
I added some more specifications for edge cases

**Comment by FnayouSeif** [comment]
For this @positiveimpact  : 
If this ProjectMember has the role Creator in the project, they should have to pass an additional variable in the request appointing the new Creator. A project always has to have exactly one creator.

Shouldn't the new creator be prompted first if they want to be creator?

**Comment by positiveimpact** [comment]
> Shouldn't the new creator be prompted first if they want to be creator?
That would be ideal, but so far the creator had all rights including appointing a new creator or new administrators. So I wouldn't make it too complicated for now and potentially change it when we run into problems with that.

**Comment by FnayouSeif** [comment]
So this should be done after my last commits. I tested it with Postman but I feel that I might be missing few edge cases. 

Summary: 
1. If User leaves a project and he is the only member (also creator), the project is flagged as inactive across climateconnect. I added a new flag column in `organization_project` called `is_active`. 
2. If User leaves a project as a creator without supplying in a post request the key "new_creator" (value should be the url_slug of user_profile), request will be denied. Otherwise, the User is set as inactive in ProjectMember, the new creator will be set as a Creator in ProjectMember, and Parent in ProjectParents 
3. If the user leaves the project and he is member, he will be flagged as in_active in ProjectMember. 

Kindly review my code before I can PR.

**Comment by ddhanesha** [comment]
@FnayouSeif  and @positiveimpact , If project only has one member (i.e. creator itself) we should give them an option to delete (or a soft delete) the project. 

We could also have a separate API to make someone else a new creator of a project. 
Question: Are we thinking about deleting project member object if someone leave a project?

**Comment by FnayouSeif** [comment]
1. In my opinion, hard deletes should be always avoided for audit reasons. However, I am not really familiar yet with the design patterns in the project. Should we always hard delete? soft delete? or it depends? 
2. For the separate API, I totally agree. It is better to seperate the transactions and have a separate API to handover the project. I think it will be a useful feature. 
3. For now it is set to inactive flag in the ProjectMember. I do recommend a soft delete here for the above mentioned reasons.

**Comment by positiveimpact** [comment]
1. I think a soft delete is fine. However, it will be hard-deleted automatically if the user chooses to delete their account (for privacy reasons)
2. You can already appoint a new creator via the "manage project members" interface, so that's already taken care of
3. I agree that a soft delete is better as long as it works with data protection (which it does in this case)

**Comment by tobiasrehm** [comment]
This issue can be closed right?

**Comment by positiveimpact** [comment]
Yep
