### ISSUE TITLE
Create interfaces for allowing users to sort projects, organizations and members

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#328]
This should be a small button on the top right side  on the same height as the filter button. Clicking it should trigger a dropdown menu which allows you to sort by "recommended", "newest" or "oldest".
Selecting a different option should trigger an API call to the `/projects/` route with the current filter settings and an additional url parameter to sort the results as specified in #301

**Comment by positiveimpact** [comment]
@tobiasrehm Could you add your designs to the documentation? 
I'd leave it up to you whether to add it to this old issue or to create a new one with better documentation.

**Comment by tobiasrehm** [comment]
I'd close it and create a new one once we have a finalised new design for the "browse page"
