### ISSUE TITLE
Send notification to project members when a comment on their project is submitted

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#331]
# General
When a `ProjectComment` is submitted via the `ProjectCommentView`, all members of the corresponding project should be notified by calling the function created in #131. An E-Mail should be sent if the notification isn't viewed for 12 hours.
Depends on #131

**Comment by tobiasrehm** [comment]
The following message should be dispayed:
[UserName] left a comment on your proejct [ProjectName]: "[Comment]
