### ISSUE TITLE
Send notification to user when there is a reply to their comment

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#334]
When a user submits a ProjectComment via `ProjectCommentView` and it has a `parent_comment` all users who have commented in the thread should receive a notification. This includes the user who wrote the `parent_comment` as well as everybody else who replied to this `parent_comment`.
Additionally as with everey comment, each project team member should also be notified.

This should trigger an E-Mail if the notification stays unread for 4 hours.

**Comment by tobiasrehm** [comment]
The following message should be dispayed:
[UserName] replied to your comment: "[Comment]"
To project owner: [UserName] left a comment on your proejct [ProjectName]: "[Comment]"
