### ISSUE TITLE
Create API endpoints for asking to join an project

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#344]
# Current Behavior
Currenly users can only be added to a project by the administrator of that project using the `AddProjectMembersView`. If they are part of a project or want to join, they have to message the administrator and ask them to add them

# New feature
Users should be able to make a request to join an project. We will most likely need a new database table for this.
### The following changes will need to be made
- Create endpoint for users to submit a request to join a project. This should create an entry in a new table `JoinProjectRequest` if there isn't already an open/declined one for this user to join this project. It should include the user, the project they're trying to join, a text describing why they want to join, a date when the join request was created and a boolean whether it was accepted. It should also trigger a notification to the project administrators. If they don't read the notification for 12 hours, they should be sent an email. 
- Create endpoint for project administrators and owners (Role should be `Read/Write` or `All`) to get all join requests to their project
- Create endpoint for declining a join request. It should edit the corresponding `JoinProjectRequest`(accepted=false) and send a notification to the user who made the initial join request
- Create endpoint for accepting a join request. It should edit the corresponding `JoinProjectRequest`(accepted=true) and add the user as a member to the corresponding project
- Check if there is a pending `JoinProjectRequest` whenever a user gets added to a project via `AddProjectMembersView`. If there is one, set accepted=true

**Comment by FnayouSeif** [comment]
What scheduler do we use actually? How would you trigger the 12 hours notification?

**Comment by positiveimpact** [comment]
We actually don't have that yet. There's an issue to [set up celery](https://github.com/climateconnect/climateconnect/issues/419) but it's not started yet. For the start it's fine if the email is sent directly. That's how we currently do it for other things as well!

**Comment by positiveimpact** [comment]
Can this one be closed?
