### ISSUE TITLE
Allow tagging users and projects in comments when you mention them

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#381]
## Current behavior
When a user wants to notify another user about a project, they have to send them the link in a private chat

## Expected future behavior
Allow tagging users, organizations and projects in project comments and private messages to notify them or recommend somebody to to contact them.

## Detailled explanation
- When you type an '@' sign in a private message or a project comment, you should get an indicator (e.g. a [tooltip](https://material-ui.com/components/tooltips/)) telling you that you can tag a user if you type the user's name
- When you start typing characters after the '@' sign, you should be able to search through users, organizations and projects by name. The functionality from [AutoCompleteSearchbar](https://github.com/climateconnect/climateconnect/blob/master/frontend/src/components/search/AutoCompleteSearchBar.js) should come in handy here
- When a user selects one of the suggested options from the search results, the tag is complete and should be visually marked, similar to GitHub, e.g. when I tag **@samschaevitz** 
- When the comment or private message is sent, the tag should become a link pointing to the profile of the mentioned person (with `target=_blank`)
- For example when you tag somebody, the actual text being saved could be something like @{first_name: "string", last_name: "string2", url_slug: "string3", type: "projects"} which could then be rendered as `<Link href="/projects/string3">{first_name + " " + last_name}</Link>` by [MessageContent](https://github.com/climateconnect/climateconnect/blob/master/frontend/src/components/communication/MessageContent.js). If you do it like this, I don't think you'll have to make any changes to [SendChatMessagesView](https://github.com/climateconnect/climateconnect/blob/master/backend/chat_messages/views/message_views.py) or the new_message function in [chat_messages/consumer.py](https://github.com/climateconnect/climateconnect/blob/master/backend/chat_messages/consumer.py). Rendering the tagging as a tagging would be completely handled in frontend.
- When you tag somebody in a comment, that person should additionally receive a notification saying that they were mentioned and linking to the comment.
    - You'll have to create a new notification type and write code for how to render it in [Notification.js](https://github.com/climateconnect/climateconnect/blob/master/frontend/src/components/communication/notifications/Notification.js)
    - You'll have to add a new Notification type to the [Notification](https://github.com/climateconnect/climateconnect/blob/master/backend/climateconnect_api/models/notification.py) model in the backend. You should be able to reuse the column project_comment to link to the particular comment

**Comment by tobiasrehm** [comment]
this is implemented so will close it
