### ISSUE TITLE
unnecessary warning message when leaving a page after writing a comment

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#385]

**Comment by positiveimpact** [comment]
The warning message is displayed when the server hasn't responded yet to the comment you've sent to it. This should only happen when there's still a loading icon next to the comment. This could actually be helpful when you lose your internet connection or something similar and could prevent you from losing your comment. In the worst case you can just go back (or forward) anyways. 
Did this happen regularly even after you gave the server some time after sending the comment?

**Comment by positiveimpact** [comment]
Closing this for now because there don't seem to be any problems on the current live version
