### ISSUE TITLE
Automatically sort users by whether they have a profile image

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#391]
# Current behavior
User profiles get sorted by `-id` which means the newest users will be shown first when displaying a list of users

# Expected future behavior
User profiles get sorted first by whether they have a profile picture and then by `-id`. This means that first all users with a profile picture are shown (newest first) and then all users without a profile picture are shown (newest first)

# Reasoning and explanation
We want users to feel more like part of a group of people when joining the platform and that's easier when they see some other people when looking at the members rather than seeing the default avatar.

Therefore whenever data is fetched from the `UserProfiles` table, it should be sorted by whether the user has a profile image. Users with a profile image should be shown first. 
This can be achieved by altering the `UserProfile` model in `/backend/climateconnect_api/models/user.py` and changing the `ordering` Meta property.

**Comment by bulve** [comment]
User profiles can be sorted by multiple properties but when properties do not overlap, it does not charge the order and all items will be sorted by only the first property which in our case is the **id**, so sorting by multiple properties where none are overlapping doesn't make sense. 

When ordering by multiple fields, at first records from DB will be ordered by the first field and later by the next field, and so on. Ordering by the next field will be performed only on groups of records that are equal by the field value ordered previously (Ex. all records with id 5). So when ordering by unique field, the result will always stay the same, second field ordering will not make any difference in the final result.

**One solution** would be to order user profiles only by image and leave null values last, but that would mean ordering will be performed on the image name in descending or ascending order, which also doesn't make sense.

**Another solution** would be to perform ordering on records after they are retrieved from DB. I would iterate through records and move the records with the image null to the end of the list.

@positiveimpact, @ddhanesha please let me know what you think.

**Comment by positiveimpact** [comment]
I see the problem, I didn't think of the fact that sorting by image would mean it automatically sorts by image name.
I would try the following things in this order:
- It's possible to use (`<field_name>__isnull`)[https://docs.djangoproject.com/en/3.1/ref/models/querysets/#std:fieldlookup-isnull] when filtering in django. Maybe this can also be used in the model's `ordering` property directly
- The accepted answer here also seems like a good option: https://stackoverflow.com/questions/9648736/django-order-by-isnull-value
- I don't think retrieving from the db and then ordering is a real option. Instead if we choose this solution, I would use an [aggregation](https://docs.djangoproject.com/en/3.1/topics/db/aggregation/) in the query, if we find a way to do that
