### ISSUE TITLE
Create database table to store users

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#4]
Sketches for layout(s):
- [profiles.json](https://github.com/climateconnect/climateconnect/blob/develop/public/data/profiles.json)
- [profile_types.json](https://github.com/climateconnect/climateconnect/blob/develop/public/data/profile_types.json)
- [profile_info_metadata.json](https://github.com/climateconnect/climateconnect/blob/develop/public/data/profile_info_metadata.json)

**Comment by positiveimpact** [comment]
A sketch of how the table structure could look like can be found here: https://github.com/climateconnect/climateconnect/blob/develop/public/data/profiles.json

**Comment by ddhanesha** [comment]
I think #147 and #148 has covered this issue.
