### ISSUE TITLE
Create progress component

### ISSUE THREAD

**Issue by ReeceLangerock** [climateconnect/climateconnect#41]
Relates to #14 

Create a generic progress display component

**Comment by positiveimpact** [comment]
I put the progress component in the design, but tbh I wasn't able to think of a good way to determine what to show there. We will still need this component, for example for [this page](https://xd.adobe.com/view/395518bf-7e51-4eb2-6ff2-3f1b57fdaa17-4f64/screen/7ecacdee-ef87-420b-af02-5308a40be120/Create-Account-Interface-Step-2).

**Comment by EvanHahn** [comment]
Closing in favor of #65. Material UI already has a [progress component](https://material-ui.com/components/progress/).
