### ISSUE TITLE
Set up Grafana to allow analyzing data

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#413]
[Grafana](https://grafana.com/) could be very handy to observe stats, such as how much certain features such as chat, comments, following, ... are used. We simply need to set up Grafana in Azure, connect it to our Postgres database, and create some queries.

**Comment by ddhanesha** [comment]
Started looking into documentation to setup Grafana.

**Comment by ddhanesha** [comment]
Grafana setup is done.
