### ISSUE TITLE
Set up python celery for asynchronous tasks

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#419]
This could be super useful to asynchronously handle tasks - such as adding a user to the newsletter subscription list on sign up - without having to wait for the task to finish. 
https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

**Comment by piperchester** [comment]
> This could be super useful to asynchronously handle tasks - such as adding a user to the newsletter subscription list on sign up - without having to wait for the task to finish.

Nice thinking on the use cases. Could we capture some more as we build this out, maybe in a lightweight wiki?

**Comment by positiveimpact** [comment]
> > This could be super useful to asynchronously handle tasks - such as adding a user to the newsletter subscription list on sign up - without having to wait for the task to finish.
> 
> Nice thinking on the use cases. Could we capture some more as we build this out, maybe in a lightweight wiki?

Sure! Would it make sense to create a page in the GitHub wiki for our repo? Feel free to create one, I'll add the use cases I thought of (and maybe additional ones I can come up with :D)

**Comment by piperchester** [comment]
Ok started a very simple one: https://github.com/climateconnect/climateconnect/wiki/Task-Queue-and-Message-System

**Comment by ddhanesha** [comment]
This has been done
