### ISSUE TITLE
Add Hubs overview link to "fancy footer"

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#428]
Add https://climateconnect.earth/hubs to the footer

**Comment by piperchester** [comment]
Is this the intended location you were thinking @tobiasrehm? 
<img width="839" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/1530684/106838944-0f997a00-6652-11eb-8723-3f7ca02aa0fa.png">

If so, we could potentially consolidate the columns to avoid the spacing gap, something like: 
<img width="793" alt="Screen Shot 2021-02-03 at 7 09 43 PM" src="https://user-images.githubusercontent.com/1530684/106839612-6bb0ce00-6653-11eb-80f1-7affab8c2229.png">

**Comment by tobiasrehm** [comment]
I like to also have the phone number there. So how about changing the email address to "send email" with a mailto: link  to achieve equal spacing?
