### ISSUE TITLE
Create Timeline Component

### ISSUE THREAD

**Issue by ReeceLangerock** [climateconnect/climateconnect#44]
Relates to #14 

For the progress tab on the project page, create a timeline component as seen on the bottom of https://xd.adobe.com/view/395518bf-7e51-4eb2-6ff2-3f1b57fdaa17-4f64/screen/bdf48a4e-501b-482a-a052-24f94e9e1baa/CO2-Labels-Project-Page-Project

**Comment by positiveimpact** [comment]
We should figure out whether this is part of the MVP

**Comment by positiveimpact** [comment]
We won't necessarily need this for a (semi-) closed Beta, but we'll definitely need this as well as the possibility to interact with posts before we advertise the product globally.

**Comment by positiveimpact** [comment]
This is already being developed in #14. It won't be a seperate component, because it won't be reused anywhere else.
