### ISSUE TITLE
When sending a chat message, message disappears for a second until it is send

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#460]
Create a smoother transition when sending a chat message. During the transition between the text input field and the chat messages, the send text disappears.  Right now it appears as the message is lost for a second.

**Comment by positiveimpact** [comment]
This has to do with a larger problem: Every few days websocket connections completely start working. After restarting the backend server this is resolved and everything works fine again. This has UX implications on multiple parts of the website. 
There is two things we can do here:
- Change the frontend to make it look like there's no problem (and there really isn't one, almost everything is working perfectly but just behaving a bit clunky when websockets are broken)
- Fix the root of the problem in backend somehow

**Comment by ddhanesha** [comment]
> This has to do with a larger problem: Every few days websocket connections completely start working. After restarting the backend server this is resolved and everything works fine again. This has UX implications on multiple parts of the website.
> There is two things we can do here:
> 
>     * Change the frontend to make it look like there's no problem (and there really isn't one, almost everything is working perfectly but just behaving a bit clunky when websockets are broken)
> 
>     * Fix the root of the problem in backend somehow

If its not something urgent, I think we should focus on fixing a root cause in the backend. 
Whoever investigates should I find answers to these questions: 
1) Why are we losing a websocket connection? 
2) Are there any issues with how we are connecting to redis via backend?
3) Is it an issue with total number of connection to our redis instance?

**Comment by positiveimpact** [comment]
> > This has to do with a larger problem: Every few days websocket connections completely start working. After restarting the backend server this is resolved and everything works fine again. This has UX implications on multiple parts of the website.
> > There is two things we can do here:
> > ```
> > * Change the frontend to make it look like there's no problem (and there really isn't one, almost everything is working perfectly but just behaving a bit clunky when websockets are broken)
> > 
> > * Fix the root of the problem in backend somehow
> > ```
> 
> If its not something urgent, I think we should focus on fixing a root cause in the backend.
> Whoever investigates should find answers to these questions:
> 
> 1. Why are we losing a websocket connection?
> 2. Are there any issues with how we are connecting to redis via backend?
> 3. Is it an issue with total number of connection to our redis instance?

Let's try to investigate these points in detail the next time this issue arises!

**Comment by positiveimpact** [comment]
Pretty sure this is fixed.
