### ISSUE TITLE
add how to get involved field

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#474]
add according to the design: 
[page ](https://xd.adobe.com/view/263c33d4-4ee4-441b-7c68-f4533c94f5ee-500d/screen/e3cac0bf-cd9b-48ad-b9cb-64fbb0b8e203)
[edit](https://xd.adobe.com/view/263c33d4-4ee4-441b-7c68-f4533c94f5ee-500d/screen/8e3244dd-d74b-4149-b4f6-f6e7672422e6)

option for "unofficial" meetings needed

**Comment by positiveimpact** [comment]
This is alraedy implemented.
