### ISSUE TITLE
add a share button to org profile

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#481]
share button for users to share the page on their social media /messengers. 
Add button on the bottom right of the background image 
see design [here](https://xd.adobe.com/view/263c33d4-4ee4-441b-7c68-f4533c94f5ee-500d/screen/e3cac0bf-cd9b-48ad-b9cb-64fbb0b8e203)

after clicking the share button open popup window. Maybe try to find something premade

**Comment by positiveimpact** [comment]
Closed by #792
