### ISSUE TITLE
Filter input fields depending on Organisation type

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#486]
Find the complete list [here](https://docs.google.com/document/d/1a-o17ex2u1qgwGqVgy1dqR_RiVdhh_y__MslXF1BuEI/edit)

(not finished jet)

**Comment by positiveimpact** [comment]
@tobiasrehm title and description of this issue are a bit confusing. To a certain degree we already have this. I'll close for now and would prefer if you create a new updated version if we choose to keep this.
