### ISSUE TITLE
Fix show more/show less with embedded videos on project page

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#494]
unexpected behaviour of embedded videos on the project page. I would be in favour of rather showing them than not showing them.  
https://user-images.githubusercontent.com/64414429/107846965-44db6000-6de8-11eb-9105-f9bff4480a73.mp4

**Comment by positiveimpact** [comment]
Sort of a duplicate by #506  (Will be fixed by fixing #506)
