### ISSUE TITLE
Remove the explicit indication of missing username or wrong password at login

### ISSUE THREAD

**Issue by FnayouSeif** [climateconnect/climateconnect#496]
In the login process, if the user does not exist, a message will indicate that the account does not exist. 
If the password is incorrect, a message will explicitly indicate so. 
This is a security risk. It is a common practice to issue a standard message "Invalid Email or Password".

**Comment by positiveimpact** [comment]
![Screenshot from 2023-02-10 08-39-10](https://user-images.githubusercontent.com/10531079/218031294-8137d862-b732-435d-a114-739173792f4f.png)
Seems to be fixed. Closing
