### ISSUE TITLE
Rename Comment section to Discussion

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#501]
Rename the "comments" tab to "discussion" on the project page 

# Steps
1. Find where in the code the name of the "comments" tab is specified
2. Change the text in the English and German version
3. Find other places where the "comments" section is referenced and change the text there as well if necessary

**Comment by 96RadhikaJadhav** [comment]
@tobiasrehm Can I work on it?

**Comment by ddhanesha** [comment]
> @tobiasrehm Can I work on it?

@96RadhikaJadhav Sure! 
* Please follow https://github.com/climateconnect/climateconnect/blob/master/README.md to setup climateconnect locally.
* Create a pull request to develop branch. 

Let us know if you have any questions.
