### ISSUE TITLE
rearrangement of project page top section

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#511]
When sidebar extended: move like and follow button underneath picture and make the picture smaller. 
- Text underneath buttons displays the last user to like or follow
-  "like and "follow" are clickable and show number and under names who liked or followed 
- number of individuals that liked and/or followed

Text "Created: xx/xx/xxxx" changed to "shared on: xx/xx/xxxx" and moved to top right corner
 
In progress label still undecided 

![image](https://user-images.githubusercontent.com/64414429/109284595-524d0d00-7820-11eb-8531-1ec424297788.png)

**Comment by positiveimpact** [comment]
Closing as we think we now implemented the version that we agreed on. Or do you see the need to still have an issue for this @tobiasrehm ?
