### ISSUE TITLE
Contact/organizer section

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#512]
The section that displays the contact person to send a message to as well as the organisations involved 

The section aligns with the bottom of the tabs and is scrollable. It displays:

1. Contact person with message button
2. Organisation Card form Organisation that shared the project, including the summary of the organisation
3. collaboration organisations cards. 
![image](https://user-images.githubusercontent.com/64414429/109295009-4e27ec00-782e-11eb-9ea6-4c6d1f9528c4.png)

For smaller screen sizes displayed underneath like this: 
![image](https://user-images.githubusercontent.com/64414429/109500278-55e9c980-7a96-11eb-975e-20557c40b1be.png)

**Comment by positiveimpact** [comment]
Closed as I consider this resolved. Does that work for you @tobiasrehm ?
