### ISSUE TITLE
visual refresh of Projects cards

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#516]
visual refresh according to this image: 
![image](https://user-images.githubusercontent.com/64414429/109501979-ab26da80-7a98-11eb-8637-e47bbd693c1b.png)

- [ ] Outline coulor: #E0E0E0 width: 1 pt; shadow : x:3 y:3 w:6 #000000 9%
- [ ] add Profile pictures of collaborating Organisation to card
- [ ] Icons in main colour
- [ ] add number of likes (once introduced in projects) and comments 
- [ ] add project type

**Comment by piperchester** [comment]
Really like this refresh @tobiasrehm. Can we drop the collapse animation while we're at it, and just apply a lift with a shadow on hover? I think that'd be a bit more clean and usable than the current state!

**Comment by tobiasrehm** [comment]
Would be awesome if you could implement this! Would improve the overall look a lot.
Even if its only the visual changes

**Comment by piperchester** [comment]
I'd like to take a stab at this as a small task in between the membership feature! Do you mind linking to the XD as well for async?

**Comment by positiveimpact** [comment]
This page has the new cards: https://xd.adobe.com/view/b12f4514-bd4b-47b7-b21c-0e4922baee92-e47c/screen/78c2bee9-9a6f-480e-9664-627a23a7c253/

**Comment by tobiasrehm** [comment]
What is the status of this? Seems like the pull request needs to be reviewed? @positiveimpact @ddhanesha

**Comment by ddhanesha** [comment]
@tobiasrehm the pull request is actively getting reviewed.
