### ISSUE TITLE
Create a project: create interface for specifying the details of the project

### ISSUE THREAD

**Issue by plantfansam** [climateconnect/climateconnect#52]
Mockup here: https://xd.adobe.com/view/395518bf-7e51-4eb2-6ff2-3f1b57fdaa17-4f64/screen/efb34c3b-643e-42b8-a20b-6823e460440a/Create-Project-Step-2

Calls these API route(s): 
- #11

**Comment by positiveimpact** [comment]
This should use the same codebase as #92
