### ISSUE TITLE
Filter button gets covered by "typing text"

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#521]
bug also exists in other places 

![image](https://user-images.githubusercontent.com/64414429/110349368-f01bb580-8032-11eb-98a0-23cfedbe2a43.png)

https://www.loom.com/share/7bd3b818380e47b7ad273a105e81c4b9

**Comment by piperchester** [comment]
I believe this is fixed @tobiasrehm? I'm unable to reproduce / repro: 

<img width="909" alt="Screen Shot 2021-07-07 at 7 16 36 PM" src="https://user-images.githubusercontent.com/1530684/124851697-e0b46680-df57-11eb-8cb6-d3c3a00def7a.png">
