### ISSUE TITLE
Allow adding projects, organizations, and profiles in multiple languages

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#527]
### General
For our CityHub update, we want it to be possible to display all content on the website in multiple languages. This includes content that is saved in the database as well as email templates.

### Database
The following tables need to be available in multiple languages. Each table is marked with "static" if the content rarely ever changes or "dynamic" if the content is ever-changing. We may consider using different solutions for these different types of content.
- Availabilities (static)
- Faq Questions (static)
- Faq Sections (static)
- Roles (static)
- Skills (static)
- Hubs (static)
- Hub stats (static)
- Location (static once added)
- Organization tags (static)
- Project tags (static)
- Project Statuses (static)
- Project Tags (static)
- User Profiles (dynamic)
- Comments (dynamic)
- Organizations (dynamic)
- Projects (dynamic)

**[New database layout draft](https://dbdiagram.io/d/6063fcaeecb54e10c33e0d82)**

### Email templates
We will create a german version of each email template. Depending on the user's language, the correct email template needs to be used.

#### General
All content on Climate Connect will always be available in English. However, with this PR we will allow users to add content in German as well. Therefore the german input needs to be translated.

#### Optional automatic translations
When inserting or editing dynamic content such as a project, users can choose whether to add a manual translation themselves or have the project be automatically translated. To illustrate this, [here](https://xd.adobe.com/view/263c33d4-4ee4-441b-7c68-f4533c94f5ee-500d/screen/87bf4cec-433c-4528-97b0-8984d50b31f7/) is a design draft for how this could look like for sharing a project.

#### How to do automatic translations in practice
The process in the backend is pretty straightforward if the user creates a manual translation: We just insert that translation into the translations table.
If a user chooses the automatic translation, we will have to first make an API call to a translation API for each of the texts included and then insert the result into the database. We should also mark these texts as automatic translations and display this information to the user. 
For translating texts automatically we'll create a generic function which uses the [DeepL API](https://www.deepl.com/en/docs-api/)

- [ ] Design and implement new database architecture
- [ ] Create function to translate texts using the DeepL API
- [ ] Adapt all backend views for inserting or updating content to use DeepL API and the new database infrastructure
- [ ] Adapt all backend GET views and associated serializers to the new database architecture and return locale-specific results.
- [ ] Implement frontend design for sharing a project and update the payloads
- [ ]  Implement frontend design for updating a project and update the payloads
- [ ]  Implement frontend design for creating an organization and update the payloads
- [ ]  Implement frontend design for editing an organization and update the payloads

**Comment by ddhanesha** [comment]
@positiveimpact I think location would be static but it would make sense to have the translation in a separate table.

**Comment by ddhanesha** [comment]
@positiveimpact I want to discuss more about comments table before implementing the new design.

**Comment by ddhanesha** [comment]
@positiveimpact I need to brainstorm an idea. For static tables there are 3 options
1. We create separate table for it and store translated value there
2. Keep adding new columns to the same table when we launch new language
3. Do not change database table, but use deepl API to translate value on the fly. 

Personally, I do not like no 3. because we might end up calling API more than our limit. I am debating between 1 and 2 tho. 

For simple tables, like `Availablility` table it does not make sense to have separate table. But for tables like `Faq questions` and `Hubs stats` I think it would make sense to have separate translation table. I think we should treat static tables on based on the content it that table. 
Let me know what you think.

**Comment by positiveimpact** [comment]
@ddhanesha I agree, option 3 is out of the question, but choosing the right option between 1 and 2 is tricky. 
Both would work for now and likely we won't have a huge amount of languages for a long time. 
But if we choose option 1, it will be uniform for the whole project. At the same time this would make it more likely for us to miss a translation. 

Overall I'd be slightly in favor of option 2 because it doesn't add any more tables, will likely scale fine for years and will make it less likely for us to miss translations

**Comment by positiveimpact** [comment]
For comments it could make most sense to translate them in real-time if somebody clicks on "see translation" - like on LinkedIn

**Comment by positiveimpact** [comment]
But at the same time that set-up for comments would make it really difficult to discuss with somebody who doesn't know English - let's discuss this in a call

**Comment by ddhanesha** [comment]
@positiveimpact I think Hub and Hubstats should have separate translation table. The reason being we might give this to moderator to manage the stats in the future. I think it would make sense to have a separate table for it. Let me know what you think

**Comment by positiveimpact** [comment]
@ddhanesha Yeah, I'd definitely make seperate translation tables for that

**Comment by positiveimpact** [comment]
@ddhanesha Yeah, that probably makes sense!
