### ISSUE TITLE
Create Grafana Dashboard to list members 

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#529]
### General
We want a dashboard because it looks nice. For that we will use our internal grafana to analyse data from the platform. 
In this issue we want to have an up to date list with all current members of the platform with specific information.

This table already exists but some more information needs to be added. Bellow will only be added the info missing that would need to be put after the existing ones (starting at column 8).

### Details
- [x] Table 1: List of the members
_Title:_ "Users"
_Columns:_ 
c8 "Skills" -> show their skills if they have some
c9 "Organisation" -> show their organisation if they are part of one
c10 "Project" -> show their project if they are part of one
c11 "Availability" -> show their availability

**Comment by brauliotegui** [comment]
New columns added: https://analytics.climateconnect.earth:3001/d/STIKoNuGk/users?orgId=1
