### ISSUE TITLE
Create Grafana Dashboard to analyse Organisations

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#532]
### General
We want a dashboard because it looks nice. For that we will use our internal grafana to analyse data from the platform.
In this issue we want to have a good understanding of the profile of our organisations. To do so we need to know what type of organisations we mostly have, in which sectors, with how many people and working on how many projects. Additionally, when it'll be implemented it'll be very important to see which are the skills they could offer to help the other with.

### Details

- [x] Table 1:  Summary
_Title:_ "General Information about Organisation"
_Columns:_
c1: "nbr of org" -> count the nbr of org registered
c2: "% of org who put at least 1 project"
[ c3: "% of org who put at least 1 skill to offer" ] **ATTENTION:** this info doesn't exist for now but will be implemented in the upcoming versions.

- [x] Table 2:  Analysis of organisation type.
_Title:_ "Organisation Type"
_Columns:_
c1 "Organisation type" -> display all the type of org (non profit, NGO,...) 
c2 "Nbr of org"->put the exact nbr for each type
C3: "Percentage of org" -> put the percentage that they represent compared to the total of org on the platform

ATTENTION: organisations can have 2 types which means the total will exceed 100%

### TO DO LATER BECAUSE WE DON'T HAVE THE INFO YET:

- [x] Table 3:  Analysis of organisation sectors.
_Title:_ "Organisation Sectors"
_Columns:_
c1"Organisation sectors"
c2 "Nbr of org"->put the nbr in each type
C3: "Percentage of org" -> put the percentage that they represent compared to the total of org on the platform

ATTENTION: organisations can have different sectors which means the total will exceed 100%

 Table 4: Analysis of skills 

_Context:_ Percentage of the skills organisations have. In this issue we want to have a good understanding of the skills of the organisations to see what type of organisation we should get into contact with because they could need those skills.

_Title:_ "Organisation Skills"
_Columns:_
c1"Organisation skills" -> display the list of all the skills form the platform
c2 "Nbr of org"->put the nbr of org that have each skills
C3: "Percentage of org" -> put the percentage that they represent compared to the total of org on the platform
ATTENTION: here the percentage is compared to the sum of organisations that has listed some skills and not the whole community

**Comment by brauliotegui** [comment]
in progress...table 1/2: https://analytics.climateconnect.earth:3001/d/ljxBpK8Gk/organizations?orgId=1&refresh=1h

**Comment by positiveimpact** [comment]
Great job @brauliotegui !
71% seems a bit high though, I thought it would be way lower. Are you sure that number is correct? :thinking:

**Comment by brauliotegui** [comment]
@positiveimpact you're right! I wasn't counting only the unique company ids. It's fixed now :) see if the numbers make more sense

**Comment by positiveimpact** [comment]
@brauliotegui  Great! Thanks for fixing :)
