### ISSUE TITLE
Create Grafana Dashboard to analyse Projects

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#535]
### General
We want a dashboard because it looks nice. For that we will use our internal grafana to analyse data from the platform.
In this issue we want to have a good understanding of the profile of projects. To do so we need to know what type of projects we mostly have, in which sectors, with how many people and working on how many projects. Additionally, when it'll be implemented it'll be very important to see which are the skills they would need to be to help with, and the organisation they'd like to be in contact with.

### Details

- [x] Table 1:  Summary
_Title:_ "General Information about Projects"
_Columns:_
c1: "nbr of projects" -> count the nbr of projects registered
c2: "nbr of different countries "

------

- [x] Table 2:  Analysis of Projects type.
_Title:_ "Project Type"
_Columns:_
c1 "Projects type" -> display all the type of projects (Idea, In progress, Cancelled, Recurring, Finished,) 
c2 "Nbr of projects"->put the exact nbr for each type
c3: "Percentage of projects" -> put the percentage that they represent compared to the total of projects on the platform
-> Then sort the table by the most important types

------

- [x] Table 3:  Analysis of Projects sectors.
_Title:_ "Project Sectors"
_Columns:_
c1 "Projects sectors" -> display all the sectors of projects (Wind Energy, sustainable agriculture, education,....) 
c2 "Nbr of projects"->put the exact nbr for each sector
c3: "Percentage of projects" -> put the percentage that they represent compared to the total of projects on the platform
->Then sort the table by the most important sectors

ATTENTION: projects can have different sectors which means the total will exceed 100%

------

- [x] Table 4: Analysis of skills 

_Context:_ Percentage of the skills projects would like to help with.

_Title:_ "Project Needed Skills"
_Columns:_
c1"skills" -> display the list of all the skills from the platform
c2 "Nbr of projects"->put the nbr of projects that want each skill
C3: "Percentage of projects" -> put the percentage that they represent compared to the total of projects on the platform
ATTENTION: here the percentage is compared to the sum of projects that have listed needing some skills and not the whole community

------

- [x] Table 5: Analysis of connections

_Context:_ Percentage of the connections projects would like to help with.

_Title:_ "Project Needed Connections"
_Columns:_
c1"Connections" -> display the list of all the connections project's like to be in contact with
c2 "Nbr of projects"->put the nbr of projects that want each connection
C3: "Percentage of projects" -> put the percentage that they represent compared to the total of projects on the platform
ATTENTION: here the percentage is compared to the sum of projects that have listed needing some skills and not the whole community

**Comment by brauliotegui** [comment]
in progress: https://analytics.climateconnect.earth:3001/d/DIkfiCuMk/projects?orgId=1&from=1618996001977&to=1619017601977

**Comment by brauliotegui** [comment]
tables 4/5 done

**Comment by positiveimpact** [comment]
@ImpactMaker-2 Could you check for all Grafana issues whether they are still relevant and move them to Clickup if yes? Closing them for now.
