### ISSUE TITLE
Create Grafana Dashboard to analyse users

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#538]
### General
We want a dashboard because it looks nice. For that we will use our internal grafana to analyse data from the platform. 
In this issue we want to have a good understanding of the profile of our members. To do so we need to know if they are already involved in projects, how much time they'd willing to spend and what skills they have.

### Details
- [x] Table 1: Percentage of users involved in a project OR an organisation.  In this issue we want to have a good understanding of the involvement of the members in projects and organisation to see if it's mostly people being active or ones looking for volunteering/jobs for example.

_Title:_ "User Involvement"
_Columns:_ 
c1 "% involved in project(s)" 
c2 "%involved in organisation(s)"
c3 "% displaying skills"
-> calculate the number for each column. 
E.g: If there is 65% of members being involved in an organisation, put 65% in c2,l1

- [x] Table 2: Percentage of users available per different amount of time. In this issue we want to have a good understanding of the availability of the members to see if they are more looking to volunteer or to find a full time/part-time job

_Title:_ " User Availability"
_Lines:_ 
l1 "1-10 h/week"
l2 "10-20 h/week"
l3 "20-30 h/week"
l4 "30-40 h/week"
l5 "40+ h/week"
_Columns:_
c1 "Availability"
c2: "Nbr of ppl" -> calculate the nbr of people for each period
c3: "% of ppl" -> calculate the % of people for each period

- [x] Table 3: Percentage of users that has put skills in their profile and which are the skills most people do have.  In this issue we want to have a good understanding of the skills of the members to see what type of organisation we should get into contact with because they could need those skills.

_Title:_ "User Skills"
_Columns:_ 
c1 "Skills" -> list the name of all the skills existing on the platform
c2 "Nbr of ppl having those skills" -> put the number for each skills
c3 "%of ppl having those skills" -> put the percentage (compared to the number of people who put some skills and NOT to the total of members)

**-> then sort by this table by which skills are the most used**

Create one for tutorial

**Comment by ddhanesha** [comment]
Assigning this to myself. @ImpactMaker-2 I will connect with you if I have any question.

**Comment by brauliotegui** [comment]
User Involvement added to User table: https://analytics.climateconnect.earth:3001/d/STIKoNuGk/users?orgId=1&from=1618464084637&to=1618485684637

**Comment by positiveimpact** [comment]
> User Involvement added to User table: https://analytics.climateconnect.earth:3001/d/STIKoNuGk/users?orgId=1&from=1618464084637&to=1618485684637

Awesome, great job!

**Comment by brauliotegui** [comment]
basically done --missing only the columns c3 "%of ppl" for skills and availability
