### ISSUE TITLE
Create Grafan Dashboard to analyse Interactions

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#543]
### Details

- [ ] Chart 1:  
_Title:_  "Daily Active chat (Excluding Core Members)" -> message counter
------

- [ ] Chart 2:  
_Title:_ "Daily chat messages from users (last 30 days)" -> message counter

------

- [ ] Chart 3:  
_Title:_ "Daily chat messages from users (last 30 days)" -> ID

-> Info: "Chat messages that weren't sent by members from the full time team. This means Tobi, Thomas, Chris and Julius are excluded"

------

- [ ] Chart 4:  
_Title:_ "Daily chat messages from users (last 30 days)" -> message counter

-> Info: "Chat messages that weren't sent by members from the full time team. This means Tobi, Thomas, Chris and Julius are excluded"

------
- [ ] Chart 5:  
_Title:_ "Weekly chat messages from users (since system launch)" -> ID

-> Info: "Chat messages that weren't sent by members from the full time team. This means Tobi, Thomas, Chris and Julius are excluded"

------

- [ ] Chart 6:  
_Title:_ "Monthly chat messages from users (since system launch)" -> ID

-> Info: "Chat messages that weren't sent by members from the full time team. This means Tobi, Thomas, Chris and Julius are excluded"

------

**Comment by positiveimpact** [comment]
@ImpactMaker-2 Could you check for all Grafana issues whether they are still relevant and move them to Clickup if yes? Closing them for now.
