### ISSUE TITLE
Create Grafana dashboard to track evolution from multiple indicators

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#544]
### General

This dashboard aims to give a global understanding of the evolution of main indicators composing the community on the platform.
1) Members number
2) Organisaion number
3) Projects number
4) Different countries number
5) Monthly chat messages from users

### Details

**Attention** Differentiation is being made below between tracking the evolution of a quantity ( if 10 ppl are at month A and 10 other joins at month B then number attributed to B will be 10 +10 =20) and the evolution of new sign up( every month counter is starting again to zero and just count the new sign up)

#### Members:

- [ ] Chart 1:  
_Title:_  "Members evolution"

-> Show the evolution of the number of people joining the community among time 

- [ ] Chart 2:  
_Title:_  "Sign up evolution"

-> Show the evolution of new sign up of people among time 

#### Organisations:

- [ ] Chart 3:  
_Title:_  "Organisation evolution"

-> Show the evolution of the number of organisation joining the community among time 

- [ ] Chart 4:  
_Title:_  "Sign up evolution"

-> Show the evolution of the new sign up of organisation among time 

#### Projects:

- [ ] Chart 5:  
_Title:_  "Projects evolution"

-> Show the evolution of the number of Projects joining the community among time 

- [ ] Chart 6:  
_Title:_  "Sign up evolution"

-> Show the evolution of the new sign up of Projects among time 

#### Countries:

- [ ] Chart 5:  
_Title:_  "Country evolution"
-> Display the amount of different countries on the platform

#### Interactions:

- [ ] Chart 6:  
_Title:_ "Monthly chat messages from users (since system launch)" -> ID

-> Info: "Chat messages that weren't sent by members from the full time team. This means Tobi, Thomas, Chris and Julius are excluded"

**Comment by positiveimpact** [comment]
Don't we have all of those already?

**Comment by tobiasrehm** [comment]
can't we close this @positiveimpact ?

**Comment by positiveimpact** [comment]
@ImpactMaker-2 Could you check for all Grafana issues whether they are still relevant and move them to Clickup if yes? Closing them for now.
