### ISSUE TITLE
Unexpected error when clicking show projects on hub page during tutorial

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#554]
during the step "want to get involved in the sector?" while logged in a bug resulted in an unexpected error happened 
![image](https://user-images.githubusercontent.com/64414429/112657153-694c4280-8e52-11eb-9b46-9b97a9b72b29.png)

seems to only happen when coming from the browsepage

**Comment by piperchester** [comment]
https://climateconnect.slack.com/archives/CPZPNBVKR/p1625724923002800?thread_ts=1625710426.001200&cid=CPZPNBVKR


More repro notes:

<img width="1128" alt="Screen Shot 2021-07-08 at 7 13 09 AM" src="https://user-images.githubusercontent.com/1530684/124937153-fbb8c200-dfbb-11eb-8330-9355a7ba90fe.png">

**Comment by positiveimpact** [comment]
Seems to be resolved.
