### ISSUE TITLE
Allow translating project in "share project" workflow

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#560]
Sub-issue of #527 

All projects should be available in English and German.

**Frontend**
An additional step for translating the project should be added at the end of the "Share project" process according to [this design](https://xd.adobe.com/view/263c33d4-4ee4-441b-7c68-f4533c94f5ee-500d/screen/87bf4cec-433c-4528-97b0-8984d50b31f7/)
- Clicking on "Automatically translate text" should fetch an automated translation from the DeepL API and display it in the corresponding fields. Users should then still be able to edit those translations. If you have already filled out one or more of the translation fields, you should be able to select in a popup "overwrite my translations", "Just translated empty fields automatically" or "cancel"
- When clicking "Skip" (could rename this to "finish"), all empty fields will be marked to automatically be translated and then be translated on the server side.

**Backend**
- Create an endpoint for just translating the contents of a project. This endpoint should be called when clicking "automatically translate text"
- Add logic for automatically translating text fields for which the user didn't pass a translation
- Insert translated version of the project into the corresponding translation table

**Comment by ddhanesha** [comment]
@positiveimpact did you start working on this already?
