### ISSUE TITLE
Translate all static database content

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#563]
Sub-issue of #527

Includes translating contents of 

- [ ] Availabilities
- [ ] Faq Questions
- [ ] Faq Sections
- [x] Roles
- [x] Skills
- [x] Hubs
- [x] Hub stats
- [x] Organization tags
- [x] Project tags
- [ ] Project Statuses

**Comment by ddhanesha** [comment]
@positiveimpact is there anything left to be done here?
