### ISSUE TITLE
Create idea board to ease people into sharing ideas and projects

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#584]
Ideaboard: https://xd.adobe.com/view/55e3ed3e-15a2-414e-911a-61b97a44bae9-00b0/screen/54bdc188-086c-435c-ad2b-6c4d11b2236b

https://xd.adobe.com/view/263c33d4-4ee4-441b-7c68-f4533c94f5ee-500d/screen/8b4c183e-c3b5-4764-aed6-526773ad8f5a

**Comment by ddhanesha** [comment]
I will be creating more tickets to split this work into multiple smaller tasks.

**Comment by ddhanesha** [comment]
@tobiasrehm @positiveimpact I am working on database design right now. I had a question about the badges on these board. Are they fixed badges for each idea or will it change for different ideas? 

<img width="146" alt="Screen Shot 2021-04-29 at 9 47 11 PM" src="https://user-images.githubusercontent.com/15343711/116649578-774f2080-a934-11eb-8306-3a8dae325cc8.png">

**Comment by tobiasrehm** [comment]
The badge symbolises the Hub or category that the idea fits in. So it can
be changed by the user when submitting or editing an idea.

Am Fr., 30. Apr. 2021 um 06:48 Uhr schrieb Dip Dhanesha <
***@***.***>:
