### ISSUE TITLE
Sign up process visual refresh

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#667]
Find grafics and each signup step in xd prototype below
![image](https://user-images.githubusercontent.com/64414429/125762889-7a159c97-c4a8-47a0-bfed-b173d58665b1.png)
https://xd.adobe.com/view/b12f4514-bd4b-47b7-b21c-0e4922baee92-e47c/screen/02732ce3-85be-4054-8983-f7702b98c88d/

**Comment by Idontker** [comment]
@tobiasrehm I have a couple of questions regarding this issue:
1. Have you a mobile design in mind for the sign up page? I created a simple one (see below) but it looks a bit boring.
2. I've implemented it the first screen excluding text styling (see below). Currently, I am mostly using the default styles of Material UI but some styles do not exactly match the design (e.g. card shadow, line heights). Do you want me to change them so they match your design.
---
## Current Implementation for the Mobile Design (same as old but includes a card)
![image](https://github.com/user-attachments/assets/b3518342-9282-475f-b4fb-97accf907b06)
## Current Implementation of the Design
![image](https://github.com/user-attachments/assets/637cf0ed-0c89-49c0-b217-a5dab838639e)

**Comment by tobiasrehm** [comment]
Regarding your questions:
1. I didn't create a mobile design back then, but keeping it simple like this is fine :) 
2. Would be great if you also implemented the styling as in the design. Especially making the "Signup" Headline bigger, adding the correct shdow for the card and left align the text with the input boxes would be important. 

Seeing it now I'd also say having the back arrow on the first step of sign up dosn't make a lot of sense instead I would an "X" icon top right to go back to the previous page: 
![image](https://github.com/user-attachments/assets/8d4c83dc-b25c-4c8a-97e4-cafe00bcabcc)

**Comment by tobiasrehm** [comment]
I was also thinking since we now have loads of real pictures maybe we replace the grafik with a picture from one of your events. I'll let you know about that :)

**Comment by Idontker** [comment]
Thank you for the input. I continued working on the issue and got confused with the font sizes: 
For example, the footer and header are different sizes of the live version do not match the sizes of the adobe xd design.
The maximum width is also different.
I am currently undecided which font size to use for the sign up card. If I copy it strictly from adobe the content on the card feels to big compared to e.g. the links.
@tobiasrehm can you help me clearing up the confusion?
--- 
## current version:
![image](https://github.com/user-attachments/assets/0cd3a42e-4de4-409b-9ca9-36535b6941d7)
---
## adobe xd version:
![image (1)](https://github.com/user-attachments/assets/16be2ba7-6cc5-4263-838b-df3a3cdc319f)
