### ISSUE TITLE
create_project endpoint 500s 

### ISSUE THREAD

**Issue by piperchester** [climateconnect/climateconnect#673]
Ran into this when testing locally to build out some of the UI for membership, in #669:

<img width="1889" alt="Screen Shot 2021-07-24 at 12 39 37 PM" src="https://user-images.githubusercontent.com/1530684/126879468-aeb2c09e-0929-4283-ae52-54444272631e.png">

**Comment by FnayouSeif** [comment]
do you have the backend logs?

**Comment by piperchester** [comment]
I _think_ this is related to needing the `DEEPL_API_KEY`, looking at https://climateconnect.slack.com/archives/CPZPNBVKR/p1627157189003300 -- going to test this out today.

**Comment by piperchester** [comment]
I think this will be fixed in: https://github.com/climateconnect/climateconnect/pull/674
