### ISSUE TITLE
Mobile: Hide header when scrolling down, make header smaller in General

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#727]
**Is your feature request related to a problem? Please describe.**
The header on mobile is really huge and takes up way too much space. 

**Describe the solution you'd like**
The header should be made smaller and should disappear when scrolling down and then reappear when scrolling up

**Describe alternatives you've considered**
The header could just be made smaller when scrolling down but not bigger when scrolling up

**Comment by Olaleye-Blessing** [comment]
I'd be happy to work on this.

This is what it's going to look like if I should make it smaller.
![Screenshot (230)](https://user-images.githubusercontent.com/70102539/160290247-1ebbf633-877d-4df0-a572-b69dc061a7f2.png)

**Comment by ddhanesha** [comment]
@Olaleye-Blessing thank you for your interest in Climate Connect! Why don't you work on it and create a pull request. One of our engineer will review. Let us know if you have any questions!

**Comment by positiveimpact** [comment]
> I'd be happy to work on this.
> 
> This is what it's going to look like if I should make it smaller. ![Screenshot (230)](https://user-images.githubusercontent.com/70102539/160290247-1ebbf633-877d-4df0-a572-b69dc061a7f2.png)

The smaller version you  made looks really nice and takes up way less space!
