### ISSUE TITLE
Bug: No spacing between text and image on About page

### ISSUE THREAD

**Issue by enoralecuyer** [climateconnect/climateconnect#730]
**Describe the bug**
There is not enough padding between the image and text in the carousel 'How climate connect works' on the About page.

**To Reproduce**
1. Go to https://climateconnect.earth/about
2. Scroll to the section 'how climate connect works'
3. Click right on the carousel until you reach 'Get Inspired'

**Expected behavior**
More spacing between text and image.

**Screenshots**
![about](https://user-images.githubusercontent.com/48727972/138176618-a754e393-1213-408b-8b31-94d6a1bb72c1.png)

**Desktop (please complete the following information:**
 - OS: Windows 11 OS
 - Browser: Firefox
 - Version 93

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by JoshKornfeld** [comment]
Fixed via #995
