### ISSUE TITLE
Bug: Typo in the Readme.md

### ISSUE THREAD

**Issue by enoralecuyer** [climateconnect/climateconnect#731]
**Describe the bug**
The verb 'insume' is used instead of 'assume' in the sentence: 'Note: we use Python 3, so for all instructions we insume python means python3.'

**To Reproduce**
1. Go to the Readme file of this github repository
2. Scroll down to 'Get Started'
3. Scroll down to 'Backend'

**Expected behavior**
N/A

**Screenshots**

![assume](https://user-images.githubusercontent.com/48727972/138177094-01d1e08b-df00-4a58-8a89-df99a4138a70.png)

**Comment by ddhanesha** [comment]
Hi @enoralecuyer, Thank you for reporting the bug. I have update the README file. 
By the way you are more than welcome to contribute on this repository if you think its something you can contribute to.
