### ISSUE TITLE
Bug: Mobile Sub Menue for Sector and CityHubs open on top of each other  

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#744]
Opening both submenus on mobile make then stack on each other 

**To Reproduce**
1. Go to /browse in mobile view
2. Click on SectorHubs and CityHubs

**Expected behavior**
If the second menu is opened first one should close 

**Screenshots**
![Screenshot_20211028-081318_Chrome](https://user-images.githubusercontent.com/64414429/139198147-7f9babcf-0f7f-40da-a1f8-7ddec83ab38b.png)

**Comment by positiveimpact** [comment]
fixed by #746
