### ISSUE TITLE
Bug: the Organisation Cards do not switch language for the orgs description 

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#786]
Organisations Cars seem to always show the description in the language it was added to the organisations profile originaly

Language should switch depending on which language was selected 

![image](https://user-images.githubusercontent.com/64414429/144010678-3a0bd2f8-52d4-4c46-abdf-8d3e5fd6a37c.png)

@marketajancova

**Comment by marketajancova** [comment]
Uuuuf, nice find, I will look at it later (after work) today. :-)

**Comment by positiveimpact** [comment]
Fixed by #787
