### ISSUE TITLE
Bug: Join page apply button in volunteer section is not working

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#793]
On the join page, [here](https://climateconnect.earth/join) in the volunteer section clicking the apply now buttons is not opening the pop-up but scrolls up to the top of the page. The page is caught from webflow and in the [webflow version](https://climateconnect.webflow.io/join-en) the apply button opens a popup

Happens on all devices it seems like

**Comment by positiveimpact** [comment]
That's just the template for a bug? :D

**Comment by tobiasrehm** [comment]
Jep sorry was distracted in the middle of it :D will edit later

Christoph Stoll ***@***.***> schrieb am Do., 2. Dez. 2021,
17:11:

**Comment by tobiasrehm** [comment]
update now

**Comment by positiveimpact** [comment]
Is this still relevant

**Comment by tobiasrehm** [comment]
Yes it is but not urgent. Instead of the application for I changed it to
link my email address on the button.

Am Mo., 7. März 2022 um 07:26 Uhr schrieb Christoph Stoll <
***@***.***>:
