### ISSUE TITLE
Bug: Invalid redirect URL after login

### ISSUE THREAD

**Issue by TheMeerCat** [climateconnect/climateconnect#796]
**Describe the bug**
After login, the redirect url si "//browse" and therefore it navigates to an unknown path.

**To Reproduce**

1. load the page as an anonymous user
2. try to log in, fill in the correct credentials

**Expected behavior**

You can see the loading spinner but it neveer loads, your URL is `https://climateconnect.earth//browse` and the following exception is in the console:

```
Uncaught Error: invariant: invalid relative URL, router received //browse
```

[See the attached video.](https://user-images.githubusercontent.com/18369329/144701199-6da5304c-a22f-41c0-a23d-9feb4c036f50.mov)

**Comment by positiveimpact** [comment]
Fixed by #797
