### ISSUE TITLE
Reduce static images in the frontend.

### ISSUE THREAD

**Issue by ddhanesha** [climateconnect/climateconnect#806]
## Description
According to [Google PageSpeed Insights](https://pagespeed.web.dev/report?url=https%3A%2F%2Fclimateconnect.earth%2F), we have many static images in our website that have larger image size. This is impacting our static pages to load slower.

## Acceptance Criteria
* Add solution that reduces image size but make sure it does not change the way how image looks and feels on the website.
* Manually test the changes.

**Comment by tobiasrehm** [comment]
Still relevant? Should be specified IMO @positiveimpact @ddhanesha

**Comment by positiveimpact** [comment]
> Still relevant? Should be specified IMO @positiveimpact @ddhanesha

Can be closed imo. Will close for now. If you disagree, please reopen and leave a comment @ddhanesha
