### ISSUE TITLE
Performance explainer issue

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#814]
For improving the website performance it would be the most productive if everybody looked for low-hanging fruits for improving the performance of different pages themselves.
As a reference we'll use the performance score from [Google page speed](https://pagespeed.web.dev/report?url=https%3A%2F%2Fclimateconnect.earth%2F). You'll get 1 point in the fix-it week for every 5 points the performance score is improved by and for each page that was affected (max for 3 pages). You can find hints on easy performance improvements when you scroll down on the Google Page speed site.

### How to make performance improvements:
1. Find an improvement that you would like to make, e.g. by checking the Google Page Speed hints
2. On each affected page make 3 page speed tests and note the performance score in the issue. (If there are more than 3 pages affected, doing this for 3 pages is enough)
3. Make the change and get it passed to master
4. Make 3 page speed tests on each of the pages again and note the difference in average performance score in the issue. You'll get 1 point per 5 points performance score per page (up to 3 pages). Example: Your change improved the performance score of the browse page and the project page by 10 points each --> You'll receive 2*2=4 fix-it points.

**Comment by tobiasrehm** [comment]
I'm closeing this.  Seemed to be only relevant for the fixit week.
