### ISSUE TITLE
Add Black to format backend code

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#827]
### Background
For the frontend we use the [prettier](https://prettier.io/) code formatted. Our backend code formatting is currently pretty horrible so we need to implement a similar code formatted for the backend.

### Acceptance Criteria
Select code formatted and implement it in an easy to use way. Add documentation about how to use it to PR templates. If possible, add it to CI. We should also update `Makefile` with a format command.

**Comment by piperchester** [comment]
@positiveimpact what do you think about https://black.readthedocs.io/en/stable/?
