### ISSUE TITLE
Bug: Capitalization in translated project titles is off

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#832]
**Describe the bug**
We translate all projects automatically using DeepL. Projects titles translated from german to english are not formatted as titles. This can make them look a bit weird. E.g. "Ökostrom-Kampagne der Klimabewegung 'wirklich-gruen'" gets translated to "eco power campaign of climate movement 'wirklich-gruen'".

**To Reproduce**
1. Create a project in german language (You can just reuse the title from the bug description)
2. Switch your language to english
3. See weirdly formatted project title

To work on this issue please contact me about the DeepL API Key, I'll give it to you

**Expected behavior**
The project title should be formatted as a title, e.g. "Eco Power Campaign of Climate Movement 'wirklich-gruen'". This can either be achieved by checking whether DeepL has an option for this or by checking for another library for capitalization of titles.

**Comment by rosywisteria** [comment]
Can I be assigned to this project?

**Comment by positiveimpact** [comment]
Hey @rosywisteria :wave: Thanks for offering your help! Sure, I assigned it to you :+1:

**Comment by rosywisteria** [comment]
Could I also have the DeepL API key as well?

**Comment by tobiasrehm** [comment]
Seems to be fixed
