### ISSUE TITLE
Review all security alerts for different 3 party libraries and merge them to master branch

### ISSUE THREAD

**Issue by ddhanesha** [climateconnect/climateconnect#851]
### Background
Go to this page and  review all security uppdates. 
https://github.com/climateconnect/climateconnect/security/dependabot
Once the review is complete merge them one by one locally and test it to make sure it doesn't break anything. 

### Acceptance Criteria
* Make sure you review and test all alerts before merging it to master to avoid breaking changes. 
* Test main features locally,
```
* Signup process
* Open browse page to make sure everything is working as expected
* Open hubs page (location and sector hubs) 
* Make sure chat messaging is working is expected.
* Make sure climatematch is working as expected. 
``` 

Please ask @ddhanesha or @positiveimpact if you have questions about testing

**Comment by tobiasrehm** [comment]
What is the status on this? @ddhanesha @positiveimpact

**Comment by positiveimpact** [comment]
I don't think we need an issue for this since we already have the dependabot PRs that we can see in the "Pull requests" tab. Closing.
