### ISSUE TITLE
Editing an organization: languages are mixed/wrong

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#862]
### Describe the bug
- When editing an organization that has been created in English the text shown will always be in English even if you have selected german as your language. This can be especially confusing to users who created german organizations in English before we added the dual language feature.

To Reproduce
Requirements: You'll need to have a DeepL API Key set in your env file to reproduce this.

1. Create an organization in english
2. Switch your language on the page to german
3. Click on the "Organisation bearbeiten" (Edit Organization" button.
4. All texts will be displayed in English

Expected behavior
The texts on the edit organization page should always be in the current selected language of the user. The edited text should then be translated to English (and potential future other languages) if automatic translation is selected.

**Comment by tobiasrehm** [comment]
Same as #1038 which one should we close?

**Comment by positiveimpact** [comment]
Closing this one
