### ISSUE TITLE
Bug: Filters by location in members / organisations are incomplete 

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#887]
**Bug description**
When using the filters on the platform not all profile (from ppl & org shows up)

**To Reproduce**
1. Go to "member tab"
2. Click on 'location filter' -> type "India"'
4. There only 18 ppl will appear when do actually more than 60 in the community

**Expected behavior**
We should see all the people & organisation & projects with the filters

**Screenshots**
![image](https://user-images.githubusercontent.com/57101650/152511009-b9be50ee-7a02-46db-ad02-243c8948ca77.png)
-> without filtering we can see Aqra Irfan on the browse page
-> after filter:
![image](https://user-images.githubusercontent.com/57101650/152511358-25b13146-6df5-474c-bcfc-dea286f42764.png)
 -> You see that he doesn't appear

**Comment by tobiasrehm** [comment]
Seems to be resolved
