### ISSUE TITLE
Bug: Font size for group chat titles is too big in inbox 

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#904]
**Describe the bug**
Group chat titles unexpectedly have a different styling than private chat titles in the inbox. The have a bigger font size

**To Reproduce**
1. You need at least one private chat and one group chat that you're in
2. Go to https://climateconnect.earth/inbox
3. See different title stylings

**Expected behavior**
The titles should have the same styling

**Screenshots**
![Screenshot from 2022-03-08 09-35-26](https://user-images.githubusercontent.com/10531079/157198814-4f98cf35-1aec-4855-9c58-028cf1345f4a.png)

**Comment by siuting0511** [comment]
Hi! may I claim this issue?

**Comment by positiveimpact** [comment]
@siuting0511 Definitely! :)

**Comment by siuting0511** [comment]
I hunt down the culprit component `chatTitle `, may I know if this component is responsible to render both group chat and private chat?

**Comment by siuting0511** [comment]
Hello! @positiveimpact, I am running and able to test the frontend locally, could you suggest way to get to the inbox component? because it requires authentication.

**Comment by positiveimpact** [comment]
The best way is to also run the backend and simply sign up on your local platform @siuting0511

**Comment by JoshKornfeld** [comment]
Closed by #955
