### ISSUE TITLE
Add pagination for the inbox

### ISSUE THREAD

**Issue by positiveimpact** [climateconnect/climateconnect#905]
**Is your feature request related to a problem? Please describe.**
The inbox currently doesn't support pagination which makes it quite slow because we use a large page size and is frustrating because you cannot access your oldest chats.

**Describe the solution you'd like**
Add pagination to the inbox, allow clicking next page or choosing a page.

**Describe alternatives you've considered**
Alternatively we could use infinite scrolling but pagination seems cleaner for this use case

**Additional context**
This could be implemented together with #439 to make improve user experience of the inbox

**Comment by JoshKornfeld** [comment]
Closed by #985
