### ISSUE TITLE
Make short description mandatory for organisation profiles

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#921]
When creating or editing an organisation profile it should be mandatory to enter a short description of the organisation. This was we avoid having essentially empty Org profiles which also looks bad in the Org Cards.

**Comment by siuting0511** [comment]
Hi！I am new here, I can help add an event listener to show error message if the description is left blank, can I be assigned to this task?

**Comment by positiveimpact** [comment]
Sure @siuting0511! Using the native error throwing of the form component by making the field `required` would probably be the best solution here. Thanks for working on this!

**Comment by piperchester** [comment]
Closed with #935!
