### ISSUE TITLE
Empty and Short link to Ideaboard Mittelfranken

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#923]
Create a short URL to access the Ideaboard of the Mittelfranken Hub in preparation for the Forum 1.5 Event.  This URL will be Linked in the Program of the Event. Also do not include Ideas from the Erlangen Ideaboard there. 

Current Link: https://climateconnect.earth/hubs/mittelfranken?&#ideas

**Comment by positiveimpact** [comment]
Created a short link: https://cutt.ly/ideen-franken
Still need to empty it

**Comment by tobiasrehm** [comment]
Closing as this was completed
