### ISSUE TITLE
Browse page: when logged in show personal dashboard insted of platform explanation.

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#959]
Do not show this slider when a user is loggedin

![Image](https://user-images.githubusercontent.com/64414429/178729167-6c3fdf84-953d-4ff9-b0c0-7799ef7fe647.png)

Instead have a top section like this (WIP, not final): 

![Image](https://user-images.githubusercontent.com/64414429/178729303-46051fea-2b45-4d38-a400-3fc0266b2524.png)

**Comment by tobiasrehm** [comment]
I would close this as this should be part of the upcoming bigger update. What do you think @ddhanesha and @positiveimpact ?

**Comment by positiveimpact** [comment]
Makes sense :+1:
