### ISSUE TITLE
Mark certain Notifications as read when clicking the bell

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#961]
Currently, for a notification to be marked as read users have to click every single one and visit the corresponding page.
For likes and follows, they should be marked a read when they are shown once in the notifications menu or it should be possible to dismiss a notification by clicking an x button.
For new messages and comments, they should only be marked as read when clicked on or when the message or comment was viewed.

**Comment by JoshKornfeld** [comment]
@tobiasrehm would this potentially be able to be closed with the delete notification feature in https://github.com/climateconnect/climateconnect/pull/1060?

**Comment by positiveimpact** [comment]
I'd consider this fixed by #1060. Are you fine with this @tobiasrehm ?
