### ISSUE TITLE
missing translation on about page because FAQ is only availabel in english right now

### ISSUE THREAD

**Issue by tobiasrehm** [climateconnect/climateconnect#991]
FAQ would need to be translated or this section removed from the about page 

![Image](https://user-images.githubusercontent.com/64414429/179974675-e064006a-a97a-4e24-a5af-d446a7d77071.png)

**Comment by JoshKornfeld** [comment]
Just a quick addition, all the FAQs aren't translated in the FAQ page either.

**Comment by JoshKornfeld** [comment]
Closed by #995
